--INSERT INTO band (bid, bname, avatar_url, introduction, follower_num, leader_id) VALUES (1, 'MIAOWU', 'https://xxx', 'balabala', 10, 1);
--
--# 注册
--INSERT INTO users (id, username, password, role, avatar_url, introduction, follower_num, bid) VALUES (1, 'Joe', '123456', 0, 'https://xxx', 'aaa', 1, 1);
--INSERT INTO users (id, username, password, role, avatar_url, introduction, follower_num, bid) VALUES (2, 'Erica', '78910', 0, 'https://xxx', 'bbb', 2, 1);
--INSERT INTO users (id, username, password, role, avatar_url, introduction, follower_num, bid) VALUES (3, 'XiaoMing', 'abcd', 0, 'https://xxx', 'ccc', 3, 1);